-- MySQL Script generated by MySQL Workbench
-- Mon Nov 26 14:23:38 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema scholaship
-- -----------------------------------------------------
-- ระบบงานทุน

-- -----------------------------------------------------
-- Schema scholaship
--
-- ระบบงานทุน
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `scholaship` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `scholaship` ;

-- -----------------------------------------------------
-- Table `scholaship`.`glb_school`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scholaship`.`glb_school` (
  `school_id` INT NOT NULL AUTO_INCREMENT COMMENT 'ไอดีหน่วยงาน',
  `school_code` VARCHAR(45) NULL COMMENT 'รหัสหน่วยงาน',
  `master_school_id` INT NULL COMMENT 'หน่วยงานหลัก',
  PRIMARY KEY (`school_id`),
  UNIQUE INDEX `school_code_UNIQUE` (`school_code` ASC),
  INDEX `fk_glb_school_glb_school_idx` (`master_school_id` ASC),
  CONSTRAINT `fk_glb_school_glb_school`
    FOREIGN KEY (`master_school_id`)
    REFERENCES `scholaship`.`glb_school` (`school_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'สาขาวิชา/สำนักวิชา';


-- -----------------------------------------------------
-- Table `scholaship`.`glb_student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scholaship`.`glb_student` (
  `student_id` VARCHAR(45) NOT NULL COMMENT 'รหัสนักศึกษา',
  `auto_id` INT NULL COMMENT 'ออโต้ไอดี',
  `glb_school_id` INT NULL,
  PRIMARY KEY (`student_id`),
  INDEX `fk_glb_student_glb_school1_idx` (`glb_school_id` ASC),
  CONSTRAINT `fk_glb_student_glb_school1`
    FOREIGN KEY (`glb_school_id`)
    REFERENCES `scholaship`.`glb_school` (`school_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'นักศึกษา';


-- -----------------------------------------------------
-- Table `scholaship`.`sch_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scholaship`.`sch_category` (
  `cat_id` INT NOT NULL AUTO_INCREMENT,
  `nameTh` VARCHAR(255) NOT NULL COMMENT 'ชื่อประเภททุน (TH)',
  `nameEn` VARCHAR(255) NOT NULL COMMENT 'ชื่อประเภททุน (EN)',
  `status` INT NULL DEFAULT 1 COMMENT 'สถานะ @{1: เปิดใช้งาน , 0: ปิดใช้งาน }',
  `eventDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'ปรับปรุงล่าสุด',
  `glb_info_id` VARCHAR(10) NULL COMMENT 'เจ้าหน้าที่บันทึกข้อมูล',
  PRIMARY KEY (`cat_id`))
ENGINE = InnoDB
COMMENT = 'หมวดหมู่ทุน';


-- -----------------------------------------------------
-- Table `scholaship`.`sch_owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scholaship`.`sch_owner` (
  `own_id` INT NOT NULL AUTO_INCREMENT,
  `nameTh` VARCHAR(255) NOT NULL COMMENT 'ชื่อผู้ให้ทุน (TH)',
  `nameEn` VARCHAR(255) NOT NULL COMMENT 'ชื่อผู้ให้ทุน (EN)',
  `own_type` INT NULL COMMENT 'ประเภทผู้ให้ทุน @{0: รัฐบาล, 1: หน่วยงานภายใน มทส., 2 หน่วยงานรัฐบาล:, 3: รัฐวิสทหกิจ, 4: เอกชน}',
  `website` VARCHAR(255) NULL COMMENT 'เว็บไซต์ผู้ให้ทุน',
  `contact` TEXT NULL COMMENT 'ข้อมูลการติดต่อ',
  `logo` VARCHAR(255) NULL COMMENT 'โลโก้',
  `status` INT NULL DEFAULT 1 COMMENT 'สถานะ @{1: เปิดใช้งาน , 0: ปิดใช้งาน }',
  `eventDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'ปรับปรุงล่าสุด',
  `glb_info_id` VARCHAR(10) NULL COMMENT 'เจ้าหน้าที่บันทึกข้อมูล',
  PRIMARY KEY (`own_id`))
ENGINE = InnoDB
COMMENT = 'ผู้ให้ทุน';


-- -----------------------------------------------------
-- Table `scholaship`.`sch_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scholaship`.`sch_type` (
  `type_id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(5) NOT NULL COMMENT 'รหัสประเภททุน',
  `name` VARCHAR(45) NOT NULL COMMENT 'ชื่อประเภททุน',
  `status` INT NULL DEFAULT 1 COMMENT 'สถานะ @{1: เปิดใช้งาน , 0: ปิดใช้งาน }',
  `eventDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'ปรับปรุงล่าสุด',
  `glb_info_id` VARCHAR(10) NULL COMMENT 'เจ้าหน้าที่บันทึกข้อมูล',
  PRIMARY KEY (`type_id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC))
ENGINE = InnoDB
COMMENT = 'ประเภททุน';


-- -----------------------------------------------------
-- Table `scholaship`.`sch_discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scholaship`.`sch_discount` (
  `dis_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT 'ชื่อเรียกส่วนลด',
  `status` INT NULL DEFAULT 1 COMMENT 'สถานะ @{1: เปิดใช้งาน , 0: ปิดใช้งาน }',
  `eventDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'ปรับปรุงล่าสุด',
  `glb_info_id` VARCHAR(10) NULL COMMENT 'เจ้าหน้าที่บันทึกข้อมูล',
  PRIMARY KEY (`dis_id`))
ENGINE = InnoDB
COMMENT = 'คิดส่วนลด';


-- -----------------------------------------------------
-- Table `scholaship`.`sch_condition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scholaship`.`sch_condition` (
  `condition_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL COMMENT 'เงื่อนไขทุน',
  `status` INT NULL COMMENT 'สถานะ @{1: เปิดใช้งาน , 0: ปิดใช้งาน }',
  `eventDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'ปรับปรุงล่าสุด',
  `glb_info_id` VARCHAR(10) NULL COMMENT 'เจ้าหน้าที่บันทึกข้อมูล',
  PRIMARY KEY (`condition_id`))
ENGINE = InnoDB
COMMENT = 'เงื่อนไขทุน';


-- -----------------------------------------------------
-- Table `scholaship`.`sch_voucher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scholaship`.`sch_voucher` (
  `voucher_id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(5) NOT NULL COMMENT 'รหัสใบสำคัญ',
  `name` VARCHAR(45) NOT NULL COMMENT 'ชื่อเรียกใบสำคัญ',
  `status` INT NULL DEFAULT 1 COMMENT 'สถานะ @{1: เปิดใช้งาน , 0: ปิดใช้งาน }',
  `eventDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'ปรับปรุงล่าสุด',
  `glb_info_id` VARCHAR(10) NULL COMMENT 'เจ้าหน้าที่บันทึกข้อมูล',
  PRIMARY KEY (`voucher_id`))
ENGINE = InnoDB
COMMENT = 'ใช้ใบสำคัญ';


-- -----------------------------------------------------
-- Table `scholaship`.`sch_scholarship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scholaship`.`sch_scholarship` (
  `scholarship_id` INT NOT NULL AUTO_INCREMENT,
  `nameTh` VARCHAR(255) NOT NULL COMMENT 'ชื่อทุน (TH)',
  `nameEn` VARCHAR(255) NOT NULL COMMENT 'ชื่อทุน (EN)',
  `sch_cat_id` INT NOT NULL COMMENT 'หมวดหมู่ทุน',
  `sch_type_id` INT NOT NULL COMMENT 'ประเภททุน',
  `sch_dis_id` INT NOT NULL COMMENT 'คิดส่วนลด',
  `sch_own_id` INT NOT NULL COMMENT 'เจ้าของทุน',
  `detailTh` TEXT NULL COMMENT 'รายละเอียดทุน (TH)',
  `detailEn` TEXT NULL COMMENT 'รายละเอียดทุน (EN)',
  `restricted` DECIMAL(15,5) NULL COMMENT 'จำกัดยอด',
  `received` DECIMAL(15,5) NULL COMMENT 'ยอดที่ได้รับ',
  `balance` DECIMAL(15,5) NULL COMMENT 'คงเหลือ',
  `sch_condition_id` INT NOT NULL COMMENT 'เงื่อนไขทุน',
  `sch_voucher_id` INT NOT NULL COMMENT 'ใช้ใบสำคัญ',
  `orderNumber` INT NULL COMMENT 'จำกัดยอด',
  PRIMARY KEY (`scholarship_id`),
  INDEX `fk_sch_scholarship_sch_category1_idx` (`sch_cat_id` ASC),
  INDEX `fk_sch_scholarship_sch_owner1_idx` (`sch_own_id` ASC),
  INDEX `fk_sch_scholarship_sch_type1_idx` (`sch_type_id` ASC),
  INDEX `fk_sch_scholarship_sch_discount1_idx` (`sch_dis_id` ASC),
  INDEX `fk_sch_scholarship_sch_condition1_idx` (`sch_condition_id` ASC),
  INDEX `fk_sch_scholarship_sch_voucher1_idx` (`sch_voucher_id` ASC),
  CONSTRAINT `fk_sch_scholarship_sch_category1`
    FOREIGN KEY (`sch_cat_id`)
    REFERENCES `scholaship`.`sch_category` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sch_scholarship_sch_owner1`
    FOREIGN KEY (`sch_own_id`)
    REFERENCES `scholaship`.`sch_owner` (`own_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sch_scholarship_sch_type1`
    FOREIGN KEY (`sch_type_id`)
    REFERENCES `scholaship`.`sch_type` (`type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sch_scholarship_sch_discount1`
    FOREIGN KEY (`sch_dis_id`)
    REFERENCES `scholaship`.`sch_discount` (`dis_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sch_scholarship_sch_condition1`
    FOREIGN KEY (`sch_condition_id`)
    REFERENCES `scholaship`.`sch_condition` (`condition_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sch_scholarship_sch_voucher1`
    FOREIGN KEY (`sch_voucher_id`)
    REFERENCES `scholaship`.`sch_voucher` (`voucher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'ทุนการศึกษา';


-- -----------------------------------------------------
-- Table `scholaship`.`sch_announce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scholaship`.`sch_announce` (
  `announce_id` INT NOT NULL,
  `nameTh` VARCHAR(255) NOT NULL COMMENT 'ประกาศ (TH)',
  `nameEn` VARCHAR(255) NOT NULL COMMENT 'ประกาศ (EN)',
  `sch_scholarship_id` INT NOT NULL COMMENT 'ทุนการศึกษา',
  `detailTh` TEXT NULL COMMENT 'รายละเอียด (TH)',
  `detailEn` TEXT NULL COMMENT 'รายละเอียด (EN)',
  `openNumber` INT NULL DEFAULT NULL COMMENT 'จำนวนที่เปิดรับ',
  `regOepn` TIMESTAMP NULL COMMENT 'เปิดรับสมัคร',
  `regColde` TIMESTAMP NULL COMMENT 'ปิดรับสมัคร',
  `note` VARCHAR(255) NULL COMMENT 'หมายเหตุ',
  `status` INT NULL DEFAULT 1 COMMENT 'สถานะ @{1: เปิดใช้งาน , 0: ปิดใช้งาน }',
  `eventDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'ปรับปรุงล่าสุด',
  `glb_info_id` VARCHAR(10) NULL COMMENT 'เจ้าหน้าที่บันทึกข้อมูล',
  `active` INT NULL,
  PRIMARY KEY (`announce_id`, `sch_scholarship_id`),
  INDEX `fk_sch_announce_sch_scholarship1_idx` (`sch_scholarship_id` ASC),
  CONSTRAINT `fk_sch_announce_sch_scholarship1`
    FOREIGN KEY (`sch_scholarship_id`)
    REFERENCES `scholaship`.`sch_scholarship` (`scholarship_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'ประกาศรับสมัคร';


-- -----------------------------------------------------
-- Table `scholaship`.`sch_register`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scholaship`.`sch_register` (
  `code` VARCHAR(10) NULL COMMENT 'รหัสการสัมคร',
  `register_id` INT NOT NULL AUTO_INCREMENT,
  `glb_student_id` VARCHAR(45) NOT NULL COMMENT 'รหัสนักศึกษา',
  `glb_school_id` INT NULL COMMENT 'รหัสสำนัก/สาขา',
  `sch_announce_id` INT NOT NULL COMMENT 'ประกาศรับสมัคร',
  `sch_scholarship_id` INT NOT NULL COMMENT 'ทุนการศึกษา',
  `regDate` TIMESTAMP NULL COMMENT 'วันที่สมัคร',
  `confirm` INT NULL DEFAULT 0 COMMENT 'ยืนยันข้อมูลการสัมคร @{0:รอยืนยันการสมัคร,1:ยืนยันการสมัครเรียบร้อย}',
  `status` INT NULL DEFAULT 1 COMMENT 'สถานะ @{1: เปิดใช้งาน , 0: ปิดใช้งาน }',
  `eventDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'ปรับปรุงล่าสุด',
  `glb_info_id` VARCHAR(10) NULL COMMENT 'เจ้าหน้าที่บันทึกข้อมูล',
  PRIMARY KEY (`register_id`),
  INDEX `fk_sch_register_glb_student1_idx` (`glb_student_id` ASC),
  INDEX `fk_sch_register_sch_announce1_idx` (`sch_announce_id` ASC),
  CONSTRAINT `fk_sch_register_glb_student1`
    FOREIGN KEY (`glb_student_id`)
    REFERENCES `scholaship`.`glb_student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sch_register_sch_announce1`
    FOREIGN KEY (`sch_announce_id`)
    REFERENCES `scholaship`.`sch_announce` (`announce_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'สมัครทุน';


-- -----------------------------------------------------
-- Table `scholaship`.`sch_register_form`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scholaship`.`sch_register_form` (
  `register_form_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `status` INT NULL DEFAULT 1 COMMENT 'สถานะ @{1: เปิดใช้งาน , 0: ปิดใช้งาน }',
  `eventDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'ปรับปรุงล่าสุด',
  `glb_info_id` VARCHAR(10) NULL COMMENT 'เจ้าหน้าที่บันทึกข้อมูล',
  PRIMARY KEY (`register_form_id`))
ENGINE = InnoDB
COMMENT = 'ฟอมร์การสมัคร';


-- -----------------------------------------------------
-- Table `scholaship`.`sch_register_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scholaship`.`sch_register_file` (
  `register_file_id` INT NOT NULL AUTO_INCREMENT,
  `labelTh` VARCHAR(255) NOT NULL COMMENT 'ป้ายชื่อหน้าช่องกรอกข้อมูล (TH)',
  `labelEn` VARCHAR(255) NOT NULL COMMENT 'ป้ายชื่อหน้าช่องกรอกข้อมูล (EN)',
  `typeFile` VARCHAR(255) NULL COMMENT 'ประเภทไฟล์',
  `sch_register_form_id` INT NOT NULL COMMENT 'ฟอร์มกรอกข้อมูล',
  `explanationTh` VARCHAR(255) NULL COMMENT 'คำอธิบาย (TH)',
  `explanationEn` VARCHAR(255) NULL COMMENT 'คำอธิบาย (EN)',
  `want` INT NULL COMMENT 'ห้ามเป็นค่าว่าง @{1: จำเป็นต้องกรอกข้อมูล, 0: ไม่จำเป็นต้องกรอก}',
  `eventDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'ปรับปรุงล่าสุด',
  `glb_info_id` VARCHAR(10) NULL COMMENT 'เจ้าหน้าที่บันทึกข้อมูล',
  PRIMARY KEY (`register_file_id`),
  INDEX `fk_sch_register_file_sch_register_form1_idx` (`sch_register_form_id` ASC),
  CONSTRAINT `fk_sch_register_file_sch_register_form1`
    FOREIGN KEY (`sch_register_form_id`)
    REFERENCES `scholaship`.`sch_register_form` (`register_form_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'แนบไฟล์ในการสมัครทุน';


-- -----------------------------------------------------
-- Table `scholaship`.`sch_expenses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scholaship`.`sch_expenses` (
  `expenses_id` INT NOT NULL,
  `code` VARCHAR(5) NOT NULL COMMENT 'รหัสค่าใช้จ่าย',
  `name` VARCHAR(255) NOT NULL COMMENT 'ชื่อค่าใช้จ่าย',
  `amount` DECIMAL(15,5) NULL COMMENT 'จำนวนเงิน',
  `feePercent` DECIMAL(10,5) NULL COMMENT 'ค่าธรรมเนียมร้อยละ',
  `sch_scholarship_id` INT NOT NULL COMMENT 'ทุนการศึกษา',
  `status` INT NULL DEFAULT 1 COMMENT 'สถานะ @{1: เปิดใช้งาน , 0: ปิดใช้งาน }',
  `eventDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'ปรับปรุงล่าสุด',
  `glb_info_id` VARCHAR(10) NULL COMMENT 'เจ้าหน้าที่บันทึกข้อมูล',
  PRIMARY KEY (`expenses_id`),
  INDEX `fk_sch_expenses_sch_scholarship1_idx` (`sch_scholarship_id` ASC),
  CONSTRAINT `fk_sch_expenses_sch_scholarship1`
    FOREIGN KEY (`sch_scholarship_id`)
    REFERENCES `scholaship`.`sch_scholarship` (`scholarship_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'ค่าใช้จ่าย';


-- -----------------------------------------------------
-- Table `scholaship`.`sch_announce_has_expenses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scholaship`.`sch_announce_has_expenses` (
  `announce_has_expenses_id` INT NOT NULL AUTO_INCREMENT,
  `sch_announce_announce_id` INT NOT NULL COMMENT 'ประกาศรับสมัครทุนการศึกษา',
  `sch_expenses_expenses_id` INT NOT NULL COMMENT 'ค่าใช้จ่าย',
  `amount` DECIMAL(15,5) NULL COMMENT 'จำนวนเงิน',
  `feePercent` DECIMAL(15,5) NULL COMMENT 'ค่าธรรมเนียมร้อยละ',
  `status` INT NULL DEFAULT 1 COMMENT 'สถานะ @{1: เปิดใช้งาน , 0: ปิดใช้งาน }',
  `eventDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'ปรับปรุงล่าสุด',
  `glb_info_id` VARCHAR(10) NULL COMMENT 'เจ้าหน้าที่บันทึกข้อมูล',
  PRIMARY KEY (`announce_has_expenses_id`, `sch_announce_announce_id`, `sch_expenses_expenses_id`),
  INDEX `fk_sch_announce_has_sch_expenses_sch_expenses1_idx` (`sch_expenses_expenses_id` ASC),
  INDEX `fk_sch_announce_has_sch_expenses_sch_announce1_idx` (`sch_announce_announce_id` ASC),
  CONSTRAINT `fk_sch_announce_has_sch_expenses_sch_announce1`
    FOREIGN KEY (`sch_announce_announce_id`)
    REFERENCES `scholaship`.`sch_announce` (`announce_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sch_announce_has_sch_expenses_sch_expenses1`
    FOREIGN KEY (`sch_expenses_expenses_id`)
    REFERENCES `scholaship`.`sch_expenses` (`expenses_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'ค่าใช้จ่าย';


-- -----------------------------------------------------
-- Table `scholaship`.`sch_register_col`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scholaship`.`sch_register_col` (
  `register_col_id` INT NOT NULL AUTO_INCREMENT,
  `labelTh` VARCHAR(255) NOT NULL COMMENT 'ป้ายชื่อหน้าช่องกรอกข้อมูล (TH)',
  `labelEn` VARCHAR(255) NOT NULL COMMENT 'ป้ายชื่อหน้าช่องกรอกข้อมูล (EN)',
  `typeFile` VARCHAR(255) NULL COMMENT 'ประเภทไฟล์',
  `sch_register_form_id` INT NOT NULL COMMENT 'ฟอร์มกรอกข้อมูล',
  `explanationTh` VARCHAR(255) NULL COMMENT 'คำอธิบาย (TH)',
  `explanationEn` VARCHAR(255) NULL COMMENT 'คำอธิบาย (EN)',
  `want` INT NULL COMMENT 'ห้ามเป็นค่าว่าง @{1: จำเป็นต้องกรอกข้อมูล, 0: ไม่จำเป็นต้องกรอก}',
  `eventDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'ปรับปรุงล่าสุด',
  `glb_info_id` VARCHAR(10) NULL COMMENT 'เจ้าหน้าที่บันทึกข้อมูล',
  PRIMARY KEY (`register_col_id`),
  INDEX `fk_sch_register_file_sch_register_form1_idx` (`sch_register_form_id` ASC),
  CONSTRAINT `fk_sch_register_file_sch_register_form10`
    FOREIGN KEY (`sch_register_form_id`)
    REFERENCES `scholaship`.`sch_register_form` (`register_form_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'แนบไฟล์ในการสมัครทุน';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
